### ISSUE TITLE
Feature Request: Increase Line Height & Editors Height

### ISSUE THREAD

**Issue by wottpal** [medienbaecker/kirby-simplemde#11]
Hey,
sorry for disrupting your Friday once again but I was wondering if there would be a simple way to increase the editors line-height? Or maybe you feel the line-height could be increased a bit as well and we could add this to the core.

Second thing is the editors overall height: Maybe either it could adopt to its content-height (with a max-height of course) or there could be this little triangle thing in the lower-left corner to increase the editors size manually.

Dennis

**Comment by medienbaecker** [comment]
Increasing the line-height should be easily possible. I will have a closer look at it.

The editor should actually autogrow though, just like the regular textarea. Maybe that's the reason you have this weird white line? Somethings not working correctly. What version of the Panel are you using?

**Comment by wottpal** [comment]
Ok, now it makes sense, of course there is no white bar for you if the editor matches the content height, because then scrolling isn't possible at all. I tried it with a clean Kirby&Panel installation and your plugin works as expected for me.. So I had to continuously disable all of my 10.000 plugins to find the one which it is interfering with. And here it is: https://github.com/JonasDoebertin/kirby-visual-markdown. It was my old Markdown field which was **only** installed under the `site/fields` directory - It was not even in use anywhere... If I delete the folder everything works :) BTW all my tests were on the latest version (2.5.8). And I can reproduce this "bug" when I install the [markdown](https://github.com/JonasDoebertin/kirby-visual-markdown)-field in my fresh installation.

So if I could increase the line-height a bit I've found my new default Kirby 2 text editor 🎉 

Thank you so much for your fast help!
Dennis

**Comment by medienbaecker** [comment]
That's really weird. I guess it has something to do with both plugins using CodeMirror. Oh well, I guess you won't need both editor plugins anyway.

Increasing the line-height was actually a very good idea. It was set to `1.2` and I now set it to `1.5`. [Looks a lot better](https://github.com/medienbaecker/kirby-simplemde/releases/tag/1.3.13)!

![lineheight](https://user-images.githubusercontent.com/7975568/34639596-b55453ca-f2e2-11e7-883d-cb7430bd3358.gif)
