### ISSUE TITLE
install with kirby cli

### ISSUE THREAD

**Issue by strukturart** [medienbaecker/kirby-simplemde#15]
Hello,
is it possible to install your plugin with the kirby cli ?

**Comment by medienbaecker** [comment]
Yes, you should be able to install this by typing `plugin:install medienbaecker/kirby-simplemde`.

<img width="738" alt="bildschirmfoto 2018-01-29 um 06 49 37" src="https://user-images.githubusercontent.com/7975568/35495324-ac994778-04c0-11e8-8a50-398a983dba08.png">
