### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by georgobermayr** [medienbaecker/kirby-simplemde#17]
Hi,

Great plugin!
Sadly it doesn't seem to work with IE 11 (wich our client needs to use), the buttons are missing and the highlighting is also not working.
Is this a bug or did you intentionally not support IE 11?

Kind regards,
Georg

**Comment by medienbaecker** [comment]
Hi Georg,

thanks for letting me know about this issue. I managed to fix it an released [version 1.3.16](https://github.com/medienbaecker/kirby-simplemde/releases/tag/1.3.16). Sorry for the inconveniences for your client.

Cheers,
Thomas
