### ISSUE TITLE
<hr> line bug

### ISSUE THREAD

**Issue by tmnssn** [medienbaecker/kirby-simplemde#19]
Hi,
Love the plugin! Really makes editing text a lot easier. 

However, I seem to run into a problem with the horizontal-rule button: instead of inserting three dashes, it inserts five. When I hit save, a \ gets added in front of the five dashes (-----) and no `<hr>` line shows up on the page, but simply five dashes (no \ either).

This also happens when I manually type four, five or any number of dashes over three. Only three dashes seems to return an `<hr>` line.

**Comment by medienbaecker** [comment]
Hey @tmnssn,

I have just pushed a fix to your issue: https://github.com/medienbaecker/kirby-simplemde/releases/tag/1.3.18
