### ISSUE TITLE
"undefined" when using the page link

### ISSUE THREAD

**Issue by jiserra** [medienbaecker/kirby-simplemde#21]
I just installed the plugin and when I try to use the page-link feature, it says "undefined".

Here's an example:
![undefined](https://user-images.githubusercontent.com/768734/37313830-4dc845cc-2627-11e8-9d4c-7255e29e4762.gif)

**Comment by medienbaecker** [comment]
It looks like the field can't find the `translation.json` and `index.json` for the page link functionality.
Do you have any custom panel routes? Or other custom fields that use custom panel routes?

I set up the routes in these lines: https://github.com/medienbaecker/kirby-simplemde/blob/master/simplemde.php#L16-L31

**Comment by jiserra** [comment]
No, I don't have anything like that.

I see on my logs that there's a 404 for this two files:
```
/panel/plugins/simplemde/index.json - No such file or directory
/panel/plugins/simplemde/translation.json - No such file or directory

**Comment by medienbaecker** [comment]
It's looking for those files because of the routes I set up in the lines I linked above. Are you sure you don't have any other plugins or fields that may use custom routes? Or maybe a custom folder setup?

If you want you can send me a zip of your website via email: mail@medienbaecker.com

**Comment by medienbaecker** [comment]
@jiserra While developing the `image` feature I might have accidentally fixed your issue, could you check? Thanks!

https://github.com/medienbaecker/kirby-simplemde/tree/feature/image

**Comment by jiserra** [comment]
Nope, sorry, the error is still there with that brunch… still says "undefined" 😢

**Comment by timpulver** [comment]
Same for me.
I’m using the multi-lang template as a starting point and the only other plugin I am using is [kirby-ref](https://github.com/floriankarsten/kirby-ref).

Same log message as @jiserra:

```
/panel/plugins/simplemde/translation.json - No such file or directory
```
