### ISSUE TITLE
'Replace textarea' Hides Certain Buttons in Structure Field Modals

### ISSUE THREAD

**Issue by luxlogica** [medienbaecker/kirby-simplemde#23]
When we use the standard 'textarea' fields in structure field modals, not all of the buttons are displayed - i.e., the buttons that require another modal/dialogue are automatically hidden (like the 'link' button).

When using the 'replace textarea' config of SimpleMDE, to get it to automatically replace all textareas in a site, the same thing happens: the same buttons that would normally be hidden in the structure field modal for a 'normal' textarea are also hidden for an auto-replaced 'simplemde' field - e.g., the 'link' field is automatically hidden, even though the field used is now indeed a 'simplemde' field, not a 'textarea'...

**Comment by luxlogica** [comment]
@medienbaecker it's one of those 'damned if you do, damned if you don't' situations! Either way, there is no 'elegant' solution, and the end user is going to have to work around the limitations imposed by the native textarea field.

My suggestions at this point would be to simply add something to the docs, to let the developer know that if using it as a 'default' replacement via config, the 'link' and 'email' buttons will also be missing - and teaching them that the workaround is to simply declare the field type as 'simplemde' in that situation, instead of 'textarea'. That should be enough! :-)

**Comment by medienbaecker** [comment]
Great idea! I added it to the README in the new branch 👍
