### ISSUE TITLE
Problem with TexField not found 

### ISSUE THREAD

**Issue by elenaramirez** [medienbaecker/kirby-simplemde#28]
Hello! I've just put your plugin in the folder you say (site/plugins) but i'm having a problem with it. 
Kirby debugger mode launches an ErrorException "Class Textfield not found". 

Do you know what could happen? My kirby version is v2.5.12. 

I would like badly to try this plugin so any help would be very appreciated :)

**Comment by medienbaecker** [comment]
Weird. The core Textfield is what this plugin is based on. Seems like your `panel` folder is not complete. Could you try down/uploading the `kirby` and `panel` folders again?
