### ISSUE TITLE
As default for all textareas

### ISSUE THREAD

**Issue by schnti** [medienbaecker/kirby-simplemde#5]
Is it possible to add this plugin as default for all default textareas?

**Comment by medienbaecker** [comment]
Possible: Yes. A good idea: I'm not sure.
I used to do this with the Enhanced Textarea because it was based on the default textarea. This one is completely different though.

Maybe an optional option in the `config.php` would be a better way to handle this.

**Comment by medienbaecker** [comment]
@schnti I added an option on the develop branch that let's you replace the core textarea:
https://github.com/medienbaecker/kirby-simplemde/tree/develop#replace-core-textarea

Does that work for you?
