### ISSUE TITLE
Content only visible after click 

### ISSUE THREAD

**Issue by zvaehn** [medienbaecker/kirby-simplemde#9]
Hey, 
it seems that the content of the simplemde is only visible after clicking into the textarea.
I was a bit confused because i first thought i had no content set.

Is there a way to fix this?

Best,
Sven

**Comment by medienbaecker** [comment]
I can't reproduce this on any of my browsers. What browser are you using? Could you provide a screenshot? Thanks!

**Comment by zvaehn** [comment]
Thanks for the reply!

Here is how it looks like: https://www.dropbox.com/s/78tcneqfm89bm9a/kirby-simplemde.mov?dl=0

I found out, that there is an issue with another plugin. If i remove it, it works fine.
Do the textareas have to be visible at the page load?

**Comment by medienbaecker** [comment]
Ah, I see. Yes, CodeMirror requires the textarea to be visible for the initial rendering. I could add a `setTimeout()` with `editor.refresh()` though. What other plugin do you mean?
If you're using a tabs plugin I would suggest trying switching over to https://github.com/afbora/Kirby-Tabs-Field as this won't set the invisible fields to `display: none`.

**Comment by zvaehn** [comment]
Jep. I use this plugin written by me: https://github.com/Klickmeister/kirby-panel-accordion
So i fixed that issue: https://github.com/Klickmeister/kirby-panel-accordion/commit/5352f4d924304fd6534b46b602be1999a0129a1b

I think that this is a smarter way instead of refreshing the editor.

Thank you :)
